<nav id="enhancement2">
    <span class="logo"><a href="https://youtu.be/KAIC4oCGNNc" target="_blank">SonixWave</a></span>
    <button class="menu-toggle" aria-expanded="false" aria-label="Toggle navigation">☰</button>
    <ul class="nav-links">
            <li><a href="index.php">Home</a></li>
            <li><a href="jobs.php">Career</a></li>
            <li><a href="apply.php">Apply Now</a></li>
            <li><a href="about.php">About Us</a></li>
            <li><a href="enhancements.php">Enhancements</a></li>
            <li><a href="manage.php">Manage</a></li>
            <li><a href="mailto:105028463@student.swin.edu.au,105192148@student.swin.edu.au">Contact</a></li>
    </ul>
</nav>