<nav id="enhancement2">
    <span class="logo"><a href="https://youtu.be/KAIC4oCGNNc" target="_blank">SonixWave</a></span>
    <ul class="nav-links">
            <li><a href="index.html">Home</a></li>
            <li><a href="jobs.html">Career</a></li>
            <li><a href="apply.html">Apply Now</a></li>
            <li><a href="about.html">About Us</a></li>
            <li><a href="enhancements.html">Enhancements</a></li>
            <li><a href="mailto:105028463@student.swin.edu.au,105192148@student.swin.edu.au">Contact</a></li>
    </ul>
</nav>